language: node_js
node_js:
- "stable"
install:
  - npm install
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage